update public.portal_documents
set session_id = null
where session_id in (
  select id
  from public.sessions
  where date between '2026-04-01' and '2026-04-03'
);

delete from public.sessions
where date between '2026-04-01' and '2026-04-03';

insert into public.speakers (slug, name, organization) values
  ('dr-bettina-love', 'Dr. Bettina Love', null),
  ('shandell-richards', 'Shandell Richards', 'Horton''s Kids'),
  ('erica-ahdoot', 'Erica Ahdoot', 'Horton''s Kids'),
  ('lex-ballard', 'Lex Ballard', 'Horton''s Kids'),
  ('darby-hickey', 'Darby Hickey', 'DC Justice Lab'),
  ('naike-savain', 'Naïké Savain', 'Washington, D.C.-based advocate'),
  ('alexia-pitter', 'Alexia Pitter', 'FAMM'),
  ('cyril-pickering', 'Cyril Pickering', 'See Forever Foundation / Maya Angelou Schools'),
  ('shamette-franklin', 'Ms. Shamette Franklin', null),
  ('rebecca-dreyfus', 'Ms. Rebecca Dreyfus', null),
  ('dr-kamal-wright-cunningham', 'Dr. Kamal Wright-Cunningham', null),
  ('liz-ryan', 'Liz Ryan', 'Former OJJDP Administrator'),
  ('nate-balis', 'Nate Balis', 'Juvenile Justice Strategy Group'),
  ('penelope-spain', 'Penelope Spain', 'Open City Advocates'),
  ('michael-umpierre', 'Michael Umpierre', 'Center for Youth Justice at Georgetown University'),
  ('senator-van-hollen', 'Senator Van Hollen', 'U.S. Senate'),
  ('dr-tiffany-simmons', 'Dr. Tiffany Simmons', 'Mosaic IC'),
  ('julia-mascioli', 'Julia Mascioli', 'Free Minds Book Club & Writing Workshop'),
  ('tara-libert', 'Tara Libert', 'Free Minds Book Club & Writing Workshop'),
  ('sofia-dean', 'Sofia Dean', 'Free Minds Book Club & Writing Workshop'),
  ('lisa-leonard', 'Lisa Leonard', null),
  ('dr-jacqueline-stevens', 'Dr. Jacqueline Stevens', 'See Forever Foundation / Maya Angelou Schools'),
  ('stephen-johns', 'Stephen Johns', 'Intrinsic to Community / See Forever Foundation'),
  ('alison-forger', 'Alison Forger', 'See Forever Foundation'),
  ('serena-monet-lewis', 'Serena-Monet Lewis', 'See Forever Foundation / Maya Angelou Schools'),
  ('francine-umaru', 'Francine Umaru', 'Maya Angelou Academy @ New Beginnings'),
  ('dr-clarisse-mendoza-davis', 'Dr. Clarisse Mendoza-Davis', 'See Forever Foundation / Maya Angelou Schools'),
  ('members-of-the-board-of-directors', 'Members of the Board of Directors', 'SFF / MAS'),
  ('guest-surprises', 'Guest Surprises', null)
on conflict (slug) do update set
  name = excluded.name,
  organization = excluded.organization;

update public.speakers
set title = 'Movement builder and advocate'
where slug = 'naike-savain';

insert into public.sessions (session_code, placeholder_code, final_title, title, slug, category, date, starts_at, ends_at, venue, room, short_description, description, live_updates, status, published, featured, is_placeholder) values
  ('d1s1', null, null, 'Registration & Continental Breakfast', 'registration-continental-breakfast', 'breakfast', '2026-04-01', '2026-04-01T08:30:00-04:00', '2026-04-01T09:15:00-04:00', 'National Union Building', 'Lobby & Main Floor', 'Arrival window with breakfast and time to settle in before programming begins.', 'Arrival window with breakfast and time to settle in before programming begins.', null, 'scheduled', true, false, false),
  ('d1s2', null, null, 'Welcome Remarks & Land Acknowledgment', 'welcome-remarks-land-acknowledgment', 'opening_session', '2026-04-01', '2026-04-01T09:15:00-04:00', '2026-04-01T09:30:00-04:00', 'National Union Building', 'Sixth Floor North and South', 'Opening remarks to welcome attendees and frame the day ahead.', 'Opening remarks to welcome attendees and frame the day ahead.', null, 'scheduled', true, false, false),
  ('d1s3', null, null, 'Opening Keynote: Dr. Bettina Love', 'opening-keynote-dr-bettina-love', 'keynote', '2026-04-01', '2026-04-01T09:30:00-04:00', '2026-04-01T10:30:00-04:00', 'National Union Building', 'Sixth Floor North and South', 'Featured keynote conversation connected to the convening theme and the work of partnership.', 'Featured keynote conversation connected to the convening theme and the work of partnership.', null, 'scheduled', true, true, false),
  ('d1s4', null, null, 'Morning Break', 'morning-break', 'break', '2026-04-01', '2026-04-01T10:30:00-04:00', '2026-04-01T10:45:00-04:00', 'National Union Building', 'National Union Building', 'Short break between programming blocks.', 'Short break between programming blocks.', null, 'scheduled', true, false, false),
  ('d1wA', 'A', 'From Superpower to Shared Power: Building Strategic Partnerships That Sustain Community Impact', 'Workshop A', 'from-superpower-to-shared-power-building-strategic-partnerships-that-sustain-community-impact-a', 'workshop', '2026-04-01', '2026-04-01T10:45:00-04:00', '2026-04-01T12:00:00-04:00', 'National Union Building', 'Third Floor North', 'This session introduces a practical framework that helps organizations identify their core strength, assess capacity gaps, and design partnerships that are strategic, sustainable, and equity driven. Participants will engage in a guided planning lab using their own organizations or programs as case studies and will leave with a draft partnership action plan, a decision making rubric, and tools for establishing joint goals, accountability measures, and ongoing assessment practices.', 'This session introduces a practical framework that helps organizations identify their core strength, assess capacity gaps, and design partnerships that are strategic, sustainable, and equity driven. Participants will engage in a guided planning lab using their own organizations or programs as case studies and will leave with a draft partnership action plan, a decision making rubric, and tools for establishing joint goals, accountability measures, and ongoing assessment practices. Learning objectives: Identify organizational strengths and partnership gaps; Evaluate strategic partnership opportunities; Draft an action plan for sustainable collaboration.', null, 'scheduled', true, false, false),
  ('d1wC', 'C', 'Stories That Move: Crafting Your Advocacy Narrative for Change', 'Workshop C', 'famm-workshop-c', 'workshop', '2026-04-01', '2026-04-01T10:45:00-04:00', '2026-04-01T12:00:00-04:00', 'National Union Building', 'Second Floor North', 'This interactive session explores how personal and community experiences with the criminal justice system can be shaped into advocacy narratives that influence decision-makers and the public.', 'Your story is more than words. It is a tool for change. This interactive session invites educators, organizations, policymakers, advocates, and community leaders to explore how personal and community experiences with the criminal justice system can be transformed into powerful narratives that influence decision-makers and the public. Participants will begin by identifying their why, the core motivation behind the work they do, and learn how to turn that purpose into the foundation of an advocacy story. Using FAMM''s "Recipe for a Powerful Advocacy Story," attendees will craft and share their narratives in guided story labs, receive feedback, and refine their messaging to maximize impact. Learning objectives: Use storytelling as an advocacy tool for policy and systems change; Clarify an advocacy ask or action connected to a personal or community narrative; Build and refine a compelling story using FAMM''s advocacy storytelling framework.', null, 'scheduled', true, false, false),
  ('d1wD', 'D', 'Practice Informed SEL Research for Adult and Justice Involved Learners', 'Workshop D', 'practice-informed-sel-research-for-adult-and-justice-involved-learners-d', 'workshop', '2026-04-01', '2026-04-01T10:45:00-04:00', '2026-04-01T12:00:00-04:00', 'National Union Building', 'Second Floor South', 'This session examines the research partnership between Maya Angelou School and American University and the development of a social and emotional learning scale for adult learners. Presenters will discuss the evolution of the project from its initial concept through pilot testing and into future collaborations with additional schools in the Washington, DC area and beyond.', 'This session examines the research partnership between Maya Angelou School and American University and the development of a social and emotional learning scale for adult learners. Presenters will discuss the evolution of the project from its initial concept through pilot testing and into future collaborations with additional schools in the Washington, DC area and beyond. Learning objectives: Explore collaboration between researchers and practitioners; Understand SEL supports for adult and justice involved learners; Identify how partnerships can strengthen practice and evaluation.', null, 'scheduled', true, false, false),
  ('d1s9', null, null, 'Networking Lunch (Provided)', 'networking-lunch-provided', 'lunch', '2026-04-01', '2026-04-01T12:30:00-04:00', '2026-04-01T14:00:00-04:00', 'National Union Building', 'Sixth Floor North and South', 'Lunch by Spilled Milk Catering with vegetarian and non-vegetarian options, plus time to connect across the convening.', 'Lunch will be provided by Spilled Milk Catering and will include both vegetarian and non-vegetarian options. This block is designed for networking, conversation, and connection across the convening.', null, 'scheduled', true, false, false),
  ('d1s11', null, null, 'Interactive Scholar Sessions with MAPCS Scholars', 'interactive-scholar-sessions-with-mapcs-scholars', 'scholar_session', '2026-04-01', '2026-04-01T14:00:00-04:00', '2026-04-01T15:00:00-04:00', 'National Union Building', 'Second Floor North & South', 'Interactive session featuring MAPCS scholars and conversation across the convening.', 'An interactive session featuring MAPCS scholars and creating space for conversation, reflection, and connection across the convening.', null, 'scheduled', true, true, false),
  ('d1s12', null, null, 'Day One Wrap-Up', 'day-one-wrap-up', 'closing_session', '2026-04-01', '2026-04-01T15:00:00-04:00', '2026-04-01T15:30:00-04:00', 'National Union Building', 'National Union Building', 'Short closing and transition before the evening reception.', 'A short closing and transition to the evening, with time for attendees to pause, reconnect, and prepare for the reception.', null, 'scheduled', true, false, false),
  ('d1s12b', null, null, 'Open Hour in Downtown D.C.', 'open-hour-in-downtown-dc', 'transition', '2026-04-01', '2026-04-01T15:30:00-04:00', '2026-04-01T16:30:00-04:00', 'Downtown Washington, D.C.', 'Downtown Washington, D.C.', 'An open hour before the reception for attendees to recharge or explore nearby.', 'Attendees have an hour before the evening reception. Nearby options include the National Portrait Gallery and other downtown destinations within walking distance.', null, 'scheduled', true, false, false),
  ('d1s13', null, null, 'From Silos to Solutions: A Happy Hour', 'from-silos-to-solutions-a-happy-hour', 'reception', '2026-04-01', '2026-04-01T16:30:00-04:00', '2026-04-01T20:00:00-04:00', 'National Union Building', 'National Union Building Speakeasy', 'Open bar, light food, and informal networking at the National Union Building Speakeasy.', 'Join the From Silos to Solutions Happy Hour at the National Union Building Speakeasy. Light food and an open bar will be provided. Conference attendees and invited MAS/SFF staff should RSVP in advance through the Happy Hour RSVP page. Planning is centered on 125 guests, with room to stretch to 150 total attendees and up to 35 MAS/SFF staff RSVPs.', 'Use the Happy Hour RSVP page to reserve your place or join the waitlist.', 'scheduled', true, true, false),
  ('d2s1', null, null, 'Arrival & Continental Breakfast', 'arrival-continental-breakfast', 'breakfast', '2026-04-02', '2026-04-02T08:30:00-04:00', '2026-04-02T09:15:00-04:00', 'National Union Building, Washington, D.C.', 'Lobby & Main Floor', 'Arrival window with breakfast and time to settle in before programming begins.', 'Arrival window with breakfast and time to settle in before programming begins.', null, 'scheduled', true, false, false),
  ('d2s2', null, null, 'Welcome & Day Two Overview', 'welcome-day-two-overview', 'opening_session', '2026-04-02', '2026-04-02T09:15:00-04:00', '2026-04-02T09:30:00-04:00', 'National Union Building, Washington, D.C.', 'Sixth Floor North and South', 'Opening remarks to welcome attendees and frame the day ahead.', 'Opening remarks to welcome attendees and frame the day ahead.', null, 'scheduled', true, false, false),
  ('d2s3', null, null, 'Opening Keynote: Fireside Chat with Liz Ryan', 'opening-keynote-fireside-chat-with-liz-ryan', 'keynote', '2026-04-02', '2026-04-02T09:30:00-04:00', '2026-04-02T10:30:00-04:00', 'National Union Building, Washington, D.C.', 'Sixth Floor North and South', 'How Collaboration Can Produce Transformational Change', 'How Collaboration Can Produce Transformational Change', null, 'scheduled', true, true, false),
  ('d2s4', null, null, 'Coffee Break', 'coffee-break', 'break', '2026-04-02', '2026-04-02T10:30:00-04:00', '2026-04-02T10:35:00-04:00', 'National Union Building, Washington, D.C.', 'National Union Building, Washington, D.C.', 'Short break between programming blocks.', 'Short break between programming blocks.', null, 'scheduled', true, false, false),
  ('d2s5', null, null, 'Panel #1: From Silos to Systems Change: Aligning Education, Youth Justice, and Community Safety', 'panel-1-from-silos-to-systems-change-aligning-education-youth-justice-and-community-safety', 'panel', '2026-04-02', '2026-04-02T10:35:00-04:00', '2026-04-02T12:00:00-04:00', 'National Union Building, Washington, D.C.', 'Sixth Floor North and South', 'How different systems that serve young people can move from operating independently to working in coordinated, prevention focused partnership.', 'How different systems that serve young people can move from operating independently to working in coordinated, prevention focused partnership.', null, 'scheduled', true, true, false),
  ('d2s6', null, null, 'Lunch (Provided) & Networking', 'lunch-provided-networking', 'lunch', '2026-04-02', '2026-04-02T12:00:00-04:00', '2026-04-02T13:00:00-04:00', 'National Union Building, Washington, D.C.', 'Lobby & Main Floor', 'Shared meal and networking time for attendees, guests, and partners.', 'Shared meal and networking time for attendees, guests, and partners.', null, 'scheduled', true, false, false),
  ('d2wE', 'E', 'Healing, Expression, and Advocacy Through Writing', 'Workshop E', 'healing-expression-and-advocacy-through-writing-e', 'workshop', '2026-04-02', '2026-04-02T13:00:00-04:00', '2026-04-02T14:15:00-04:00', 'National Union Building, Washington, D.C.', 'Third Floor North', 'Healing, Expression, and Advocacy Through Writing', 'Healing, Expression, and Advocacy Through Writing', null, 'scheduled', true, false, false),
  ('d2wF', 'F', 'We Can’t Do This Alone: Collective Well Being in Alternative Education', 'Workshop F', 'we-can-t-do-this-alone-collective-well-being-in-alternative-education-f', 'workshop', '2026-04-02', '2026-04-02T13:00:00-04:00', '2026-04-02T14:15:00-04:00', 'National Union Building, Washington, D.C.', 'Third Floor South', 'This session explores findings from a qualitative study on the experiences of Type III alternative educators working with trauma impacted students. Participants will examine how chronic role shifting, self sacrifice, and burnout impact educators and will engage in collaborative analysis of how internal and external partnerships can support a community of well being.', 'This session explores findings from a qualitative study on the experiences of Type III alternative educators working with trauma impacted students. Participants will examine how chronic role shifting, self sacrifice, and burnout impact educators and will engage in collaborative analysis of how internal and external partnerships can support a community of well being. Learning objectives: Review key findings from research on alternative educators and trauma impacted environments; Analyze how partnerships can support educator well being and sustainability; Develop strategies to build communities that support both educators and students.', null, 'scheduled', true, false, false),
  ('d2wG', 'G', 'Intrinsic to Community: Building Purpose Driven Leadership from Within', 'Workshop G', 'intrinsic-to-community-building-purpose-driven-leadership-from-within-g', 'workshop', '2026-04-02', '2026-04-02T13:00:00-04:00', '2026-04-02T14:15:00-04:00', 'National Union Building, Washington, D.C.', 'Second Floor North', 'This session introduces the Intrinsic Leadership Model, a framework focused on self awareness, self mastery, authentic leadership, and community connection. Participants will explore how personal alignment across spiritual, physical, mental, and emotional domains strengthens leadership effectiveness and drives sustainable community impact.', 'This session introduces the Intrinsic Leadership Model, a framework focused on self awareness, self mastery, authentic leadership, and community connection. Participants will explore how personal alignment across spiritual, physical, mental, and emotional domains strengthens leadership effectiveness and drives sustainable community impact. Learning objectives: Understand the four components of the Intrinsic Leadership Model; Assess personal alignment and leadership practices; Apply strategies to build purpose driven leadership within organizations.', null, 'scheduled', true, false, false),
  ('d2s10', null, null, 'Coffee Break', 'coffee-break-transition', 'break', '2026-04-02', '2026-04-02T14:15:00-04:00', '2026-04-02T14:20:00-04:00', 'National Union Building, Washington, D.C.', 'National Union Building, Washington, D.C.', 'Short break between programming blocks.', 'Short break between programming blocks.', null, 'scheduled', true, false, false),
  ('d2wI', 'I', 'Building Youth Power in Local Policymaking', 'Workshop I', 'building-youth-power-in-local-policymaking-i', 'workshop', '2026-04-02', '2026-04-02T14:20:00-04:00', '2026-04-02T15:35:00-04:00', 'National Union Building, Washington, D.C.', 'Third Floor North', 'In this interactive workshop, participants will engage in activities to strengthen young people’s understanding of laws and policies and how to influence them. Using discussion, role play, and participatory techniques, the session explores how local policymaking happens, how to identify policymakers, how to craft a policy ask, and how to support young people in communicating with elected officials and other decision makers.', 'In this interactive workshop, participants will engage in activities to strengthen young people’s understanding of laws and policies and how to influence them. Using discussion, role play, and participatory techniques, the session explores how local policymaking happens, how to identify policymakers, how to craft a policy ask, and how to support young people in communicating with elected officials and other decision makers. Learning objectives: Understand how local policymaking works; Help young people identify policymakers and policy asks; Build youth advocacy and civic engagement skills.', null, 'scheduled', true, false, false),
  ('d2wJ', 'J', 'Intro to Moral Injury: The Impact of Harm for All Youth Justice Stakeholders', 'Workshop J', 'intro-to-moral-injury-the-impact-of-harm-for-all-youth-justice-stakeholders-j', 'workshop', '2026-04-02', '2026-04-02T14:20:00-04:00', '2026-04-02T15:35:00-04:00', 'National Union Building, Washington, D.C.', 'Third Floor South', 'This session introduces the concept of moral injury and its impact on youth, educators, and justice system stakeholders. Participants will explore how experiences of harm, witnessing harm, or systemic failure affect well being and trust. Through discussion, media, and scenario based activities, participants will develop language and frameworks to understand moral injury and its role in youth justice settings.', 'This session introduces the concept of moral injury and its impact on youth, educators, and justice system stakeholders. Participants will explore how experiences of harm, witnessing harm, or systemic failure affect well being and trust. Through discussion, media, and scenario based activities, participants will develop language and frameworks to understand moral injury and its role in youth justice settings. Learning objectives: Define moral injury and its relevance in youth justice and education settings; Identify signs of moral distress, burnout, and compassion fatigue; Develop language and strategies to process and respond to morally challenging experiences.', null, 'scheduled', true, false, false),
  ('d2wK', 'K', 'From Safe to Brave: Leading With LOVE Through Purposeful Partnerships', 'Workshop K', 'from-safe-to-brave-leading-with-love-through-purposeful-partnerships-k', 'workshop', '2026-04-02', '2026-04-02T14:20:00-04:00', '2026-04-02T15:35:00-04:00', 'National Union Building, Washington, D.C.', 'Second Floor North', 'This workshop challenges leaders to move beyond safe environments toward creating brave spaces rooted in LOVE: Leading with Love, Overflowing with Joy, Visionary, and Ethos of Care. Participants will explore how purposeful partnerships across staff, students, families, and communities strengthen trust, alignment, and impact.', 'This workshop challenges leaders to move beyond safe environments toward creating brave spaces rooted in LOVE: Leading with Love, Overflowing with Joy, Visionary, and Ethos of Care. Participants will explore how purposeful partnerships across staff, students, families, and communities strengthen trust, alignment, and impact. Learning objectives: Understand the LOVE leadership framework; Identify strategies to build purposeful and sustainable partnerships; Develop a Leadership Partnership Action Plan to implement in an organization.', null, 'scheduled', true, false, false),
  ('d2wL', 'L', 'Post-Traumatic Stress + Post-Secondary Success: The PWR of Radical Acceptance', 'Workshop L', 'post-traumatic-stress-post-secondary-success-the-pwr-of-radical-acceptance-l', 'workshop', '2026-04-02', '2026-04-02T14:20:00-04:00', '2026-04-02T15:35:00-04:00', 'National Union Building, Washington, D.C.', 'Second Floor South', 'This workshop examines how post-traumatic stress, adverse childhood experiences, and unresolved trauma influence the lived experiences of justice involved youth as they navigate postsecondary pathways. Through a trauma informed lens, the session reframes youth behaviors as adaptive responses to chronic adversity and emphasizes radical acceptance and cross system partnerships as pathways to healing, belonging, and sustained success.', 'This workshop examines how post-traumatic stress, adverse childhood experiences, and unresolved trauma influence the lived experiences of justice involved youth as they navigate postsecondary pathways. Through a trauma informed lens, the session reframes youth behaviors as adaptive responses to chronic adversity and emphasizes radical acceptance and cross system partnerships as pathways to healing, belonging, and sustained success. Learning objectives: Understand how trauma and ACEs shape youth engagement in postsecondary and workforce settings; Recognize how systems can criminalize trauma and reinforce inequitable practices; Identify collaborative strategies that support healing, belonging, and long term success.', null, 'scheduled', true, false, false),
  ('d2s15', null, null, 'Closing Announcements & Friday Preview', 'closing-announcements-friday-preview', 'closing_session', '2026-04-02', '2026-04-02T15:35:00-04:00', '2026-04-02T15:55:00-04:00', 'National Union Building, Washington, D.C.', 'Sixth Floor North and South', 'Brief closing announcements and Friday logistics before the dinner break.', 'Attendees will reconvene briefly for closing announcements and Friday logistics before the dinner break begins at 3:55 PM ahead of the evening bus tour.', null, 'scheduled', true, false, false),
  ('d2s15b', null, null, 'Dinner Break', 'dinner-break', 'break', '2026-04-02', '2026-04-02T15:55:00-04:00', '2026-04-02T18:00:00-04:00', 'Downtown Washington, D.C.', 'On Your Own', 'Dinner break before the evening Big Bus tour.', 'Attendees will have time for dinner before the evening Big Bus tour begins at 6:00 PM.', null, 'scheduled', true, false, false),
  ('d2s16', null, null, 'Big Bus Sunset Tour of Washington', 'big-bus-sunset-tour-of-washington', 'evening_event', '2026-04-02', '2026-04-02T18:00:00-04:00', '2026-04-02T20:30:00-04:00', 'Washington, D.C.', 'Meet Outside N.U.B.', 'Big Bus tour featuring cherry blossoms and Washington monuments at sunset.', 'This evening Big Bus tour will feature the cherry blossoms and Washington monuments at sunset. It is open to all conference attendees, staff, and volunteers, with space reserved for the first 50 people who sign up at registration on Wednesday morning or on Thursday if spots remain.', null, 'scheduled', true, true, false),
  ('d3s1', null, null, 'Arrival & Light Breakfast', 'arrival-light-breakfast', 'breakfast', '2026-04-03', '2026-04-03T09:30:00-04:00', '2026-04-03T10:00:00-04:00', 'Maya Angelou Learning Campus, P.A.C., Cafeteria, & Gymnasium', 'Lobby of Performing Arts Center', 'Arrival window with breakfast and time to settle in before programming begins.', 'Arrival window with breakfast and time to settle in before programming begins.', null, 'scheduled', true, false, false),
  ('d3s2', null, null, 'Welcome & Day Three Framing', 'welcome-day-three-framing', 'opening_session', '2026-04-03', '2026-04-03T10:00:00-04:00', '2026-04-03T10:10:00-04:00', 'Maya Angelou Learning Campus, P.A.C., Cafeteria, & Gymnasium', 'Performing Arts Center', 'Opening remarks to welcome attendees and frame the day ahead.', 'Opening remarks to welcome attendees and frame the day ahead.', null, 'scheduled', true, false, false),
  ('d3s2b', null, null, 'Limited Excursion: Private Tour of a Secure Site', 'limited-excursion-private-tour-of-a-secure-site', 'special_event', '2026-04-03', '2026-04-03T09:30:00-04:00', '2026-04-03T12:15:00-04:00', 'Washington, D.C.', 'Details shared with confirmed participants', 'Optional private tour of one of our secure sites in Washington, D.C., with departure beginning at 9:30 AM.', 'An optional limited excursion offering a private tour of one of our secure sites in Washington, D.C. Confirmed participants should arrive by 9:30 AM for departure to the sites and will return in time for lunch. This experience reflects our work as the exclusive provider for incarcerated education in the city. Space is limited to the first 10 attendees who sign up, and confirmed participants will receive follow-up logistics directly.', null, 'scheduled', true, false, false),
  ('d3s3', null, null, 'Maya Angelou Schools Documentary Screening', 'maya-angelou-schools-documentary-screening', 'special_event', '2026-04-03', '2026-04-03T10:10:00-04:00', '2026-04-03T10:55:00-04:00', 'Maya Angelou Learning Campus, P.A.C., Cafeteria, & Gymnasium', 'Performing Arts Center', 'Documentary screening highlighting Maya Angelou Schools and the work behind the convening.', 'Documentary screening highlighting Maya Angelou Schools and the work behind the convening.', null, 'scheduled', true, false, false),
  ('d3s4', null, null, 'Coffee Break', 'coffee-break-d3s4', 'break', '2026-04-03', '2026-04-03T10:55:00-04:00', '2026-04-03T11:10:00-04:00', 'Maya Angelou Learning Campus, P.A.C., Cafeteria, & Gymnasium', 'Lobby of Performing Arts Center', 'Short break between programming blocks.', 'Short break between programming blocks.', null, 'scheduled', true, false, false),
  ('d3s5', null, null, 'Fireside Chat and Guided Reflection with CEO Dr. Clarisse Mendoza-Davis', 'fireside-chat-guided-reflection-dr-clarisse-mendoza-davis', 'fireside_chat', '2026-04-03', '2026-04-03T11:10:00-04:00', '2026-04-03T12:15:00-04:00', 'Maya Angelou Learning Campus, P.A.C., Cafeteria, & Gymnasium', 'Performing Arts Center', 'A combined fireside chat and guided reflection led by CEO Dr. Clarisse Mendoza-Davis to formally close the convening.', 'CEO Dr. Clarisse Mendoza-Davis will lead a combined fireside chat and guided reflection to formally close the convening, bringing the conversation back to the partnership, leadership, and accountability themes that shaped the week.', null, 'scheduled', true, true, false),
  ('d3s6', null, null, 'Community Lunch', 'community-lunch', 'lunch', '2026-04-03', '2026-04-03T12:15:00-04:00', '2026-04-03T13:15:00-04:00', 'Maya Angelou Learning Campus, P.A.C., Cafeteria, & Gymnasium', 'Cafeteria', 'Shared lunch for attendees following the convening close.', 'Lunch will be served following the closing fireside chat and guided reflection.', null, 'scheduled', true, false, false),
  ('d3s7', null, null, 'Small Group Tours of the High School Campus', 'small-group-tours-of-the-high-school-campus', 'special_event', '2026-04-03', '2026-04-03T13:15:00-04:00', '2026-04-03T13:45:00-04:00', 'Maya Angelou Learning Campus, P.A.C., Cafeteria, & Gymnasium', 'High School Campus', 'Small group tours of the high school campus.', 'Attendees will have an opportunity to join small group tours of the high school campus before reconvening in the PAC.', null, 'scheduled', true, false, false),
  ('d3s8', null, null, 'Transition Back to the Performing Arts Center (PAC)', 'transition-back-to-the-performing-arts-center-pac', 'transition', '2026-04-03', '2026-04-03T13:45:00-04:00', '2026-04-03T14:00:00-04:00', 'Maya Angelou Learning Campus, P.A.C., Cafeteria, & Gymnasium', 'Campus Transition to PAC', 'Transition back to the PAC for the closing celebration.', 'Attendees will transition back to the Performing Arts Center before the Dr. Maya Angelou celebration begins at 2:00 PM.', null, 'scheduled', true, false, false),
  ('d3s9', null, null, 'Dr. Maya Angelou Birthday Celebration with Scholars & Attendees', 'dr-maya-angelou-birthday-celebration-with-scholars-attendees', 'scholar_session', '2026-04-03', '2026-04-03T14:00:00-04:00', '2026-04-03T15:30:00-04:00', 'Maya Angelou Learning Campus, P.A.C., Cafeteria, & Gymnasium', 'Performing Arts Center', 'Celebration with scholars and attendees honoring Dr. Maya Angelou and the scholar-centered spirit of the convening.', 'Celebration with scholars and attendees honoring Dr. Maya Angelou and the scholar-centered spirit of the convening.', null, 'scheduled', true, true, false);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'sessions'
      and column_name = 'signup_enabled'
  ) then
    update public.sessions
    set
      signup_enabled = true,
      signup_capacity = 50,
      signup_instructions = 'Save your spot for the Big Bus sunset tour here. Phone number is optional, but helpful if the conference team needs to send a text update. The first 50 sign-ups will be confirmed and any additional sign-ups will be placed on the waitlist.'
    where session_code = 'd2s16';

    update public.sessions
    set
      signup_enabled = true,
      signup_capacity = 10,
      signup_instructions = 'Use this form to request a spot on the limited Friday excursion. Space is available to the first 10 attendees, and sign-ups close on Wednesday, April 1. Confirmed participants will receive private location details directly.'
    where session_code = 'd3s2b';
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'sessions'
      and column_name = 'signup_deadline'
  ) then
    update public.sessions
    set signup_deadline = '2026-04-01T23:59:00-04:00'
    where session_code = 'd3s2b';
  end if;
end $$;

insert into public.session_speakers (session_id, speaker_id, session_role) values
  ((select id from public.sessions where slug = 'opening-keynote-dr-bettina-love'), (select id from public.speakers where slug = 'dr-bettina-love'), 'speaker'),
  ((select id from public.sessions where slug = 'from-superpower-to-shared-power-building-strategic-partnerships-that-sustain-community-impact-a'), (select id from public.speakers where slug = 'shandell-richards'), 'workshop_presenter'),
  ((select id from public.sessions where slug = 'from-superpower-to-shared-power-building-strategic-partnerships-that-sustain-community-impact-a'), (select id from public.speakers where slug = 'lex-ballard'), 'workshop_presenter'),
  ((select id from public.sessions where slug = 'building-youth-power-in-local-policymaking-i'), (select id from public.speakers where slug = 'darby-hickey'), 'workshop_presenter'),
  ((select id from public.sessions where slug = 'building-youth-power-in-local-policymaking-i'), (select id from public.speakers where slug = 'naike-savain'), 'workshop_presenter'),
  ((select id from public.sessions where slug = 'famm-workshop-c'), (select id from public.speakers where slug = 'alexia-pitter'), 'workshop_presenter'),
  ((select id from public.sessions where slug = 'practice-informed-sel-research-for-adult-and-justice-involved-learners-d'), (select id from public.speakers where slug = 'cyril-pickering'), 'workshop_presenter'),
  ((select id from public.sessions where slug = 'practice-informed-sel-research-for-adult-and-justice-involved-learners-d'), (select id from public.speakers where slug = 'shamette-franklin'), 'workshop_presenter'),
  ((select id from public.sessions where slug = 'practice-informed-sel-research-for-adult-and-justice-involved-learners-d'), (select id from public.speakers where slug = 'rebecca-dreyfus'), 'workshop_presenter'),
  ((select id from public.sessions where slug = 'practice-informed-sel-research-for-adult-and-justice-involved-learners-d'), (select id from public.speakers where slug = 'dr-kamal-wright-cunningham'), 'workshop_presenter'),
  ((select id from public.sessions where slug = 'opening-keynote-fireside-chat-with-liz-ryan'), (select id from public.speakers where slug = 'liz-ryan'), 'speaker'),
  ((select id from public.sessions where slug = 'panel-1-from-silos-to-systems-change-aligning-education-youth-justice-and-community-safety'), (select id from public.speakers where slug = 'nate-balis'), 'panelist'),
  ((select id from public.sessions where slug = 'panel-1-from-silos-to-systems-change-aligning-education-youth-justice-and-community-safety'), (select id from public.speakers where slug = 'penelope-spain'), 'panelist'),
  ((select id from public.sessions where slug = 'panel-1-from-silos-to-systems-change-aligning-education-youth-justice-and-community-safety'), (select id from public.speakers where slug = 'liz-ryan'), 'panelist'),
  ((select id from public.sessions where slug = 'panel-1-from-silos-to-systems-change-aligning-education-youth-justice-and-community-safety'), (select id from public.speakers where slug = 'michael-umpierre'), 'panelist'),
  ((select id from public.sessions where slug = 'panel-1-from-silos-to-systems-change-aligning-education-youth-justice-and-community-safety'), (select id from public.speakers where slug = 'senator-van-hollen'), 'panelist'),
  ((select id from public.sessions where slug = 'panel-1-from-silos-to-systems-change-aligning-education-youth-justice-and-community-safety'), (select id from public.speakers where slug = 'dr-tiffany-simmons'), 'panelist'),
  ((select id from public.sessions where slug = 'healing-expression-and-advocacy-through-writing-e'), (select id from public.speakers where slug = 'tara-libert'), 'workshop_presenter'),
  ((select id from public.sessions where slug = 'healing-expression-and-advocacy-through-writing-e'), (select id from public.speakers where slug = 'sofia-dean'), 'workshop_presenter'),
  ((select id from public.sessions where slug = 'we-can-t-do-this-alone-collective-well-being-in-alternative-education-f'), (select id from public.speakers where slug = 'dr-jacqueline-stevens'), 'workshop_presenter'),
  ((select id from public.sessions where slug = 'intrinsic-to-community-building-purpose-driven-leadership-from-within-g'), (select id from public.speakers where slug = 'stephen-johns'), 'workshop_presenter'),
  ((select id from public.sessions where slug = 'intro-to-moral-injury-the-impact-of-harm-for-all-youth-justice-stakeholders-j'), (select id from public.speakers where slug = 'alison-forger'), 'workshop_presenter'),
  ((select id from public.sessions where slug = 'from-safe-to-brave-leading-with-love-through-purposeful-partnerships-k'), (select id from public.speakers where slug = 'serena-monet-lewis'), 'workshop_presenter'),
  ((select id from public.sessions where slug = 'post-traumatic-stress-post-secondary-success-the-pwr-of-radical-acceptance-l'), (select id from public.speakers where slug = 'francine-umaru'), 'workshop_presenter'),
  ((select id from public.sessions where slug = 'fireside-chat-guided-reflection-dr-clarisse-mendoza-davis'), (select id from public.speakers where slug = 'dr-clarisse-mendoza-davis'), 'speaker')
on conflict do nothing;

update public.announcements
set body = 'Welcome to From Silos to Solutions 2026. Explore the schedule, review the latest updates, and use the portal for shared conference documents.'
where title = 'Welcome to FS2S 2026';
